truenas/apps

README.md
cspell.config.yaml
ix-dev/community/zerotier/README.md
ix-dev/community/zerotier/app.yaml
ix-dev/community/zerotier/item.yaml
ix-dev/community/zerotier/ix_values.yaml
ix-dev/community/zerotier/migrations/migration_helpers/cpu.py
ix-dev/community/zerotier/migrations/migration_helpers/dns_config.py
ix-dev/community/zerotier/migrations/migration_helpers/kubernetes_secrets.py
ix-dev/community/zerotier/migrations/migration_helpers/memory.py
ix-dev/community/zerotier/migrations/migration_helpers/resources.py
ix-dev/community/zerotier/migrations/migration_helpers/storage.py
ix-dev/community/zerotier/questions.yaml
ix-dev/community/zerotier/templates/docker-compose.yaml
ix-dev/community/zerotier/templates/library/base_v1_0_0/environment.py
ix-dev/community/zerotier/templates/library/base_v1_0_0/healthchecks.py
ix-dev/community/zerotier/templates/library/base_v1_0_0/metadata.py
ix-dev/community/zerotier/templates/library/base_v1_0_0/network.py
ix-dev/community/zerotier/templates/library/base_v1_0_0/ports.py
ix-dev/community/zerotier/templates/library/base_v1_0_0/postgres.py
ix-dev/community/zerotier/templates/library/base_v1_0_0/redis.py
ix-dev/community/zerotier/templates/library/base_v1_0_0/resources.py
ix-dev/community/zerotier/templates/library/base_v1_0_0/security.py
ix-dev/community/zerotier/templates/library/base_v1_0_0/storage.py
ix-dev/community/zerotier/templates/library/base_v1_0_0/utils.py
ix-dev/community/zerotier/templates/macros/global/perms/container.yaml.jinja
ix-dev/community/zerotier/templates/macros/global/perms/script.sh.jinja
ix-dev/community/zerotier/templates/test_values/basic-values.yaml
ix-dev/community/zerotier/templates/test_values/no-host-values.yaml

App failure is expected (No API Key)

add zerotier

---

ix-dev/community/plex-auto-languages/app.yaml
ix-dev/community/plex-auto-languages/migrations/migrate_from_kubernetes

Looks like I've never commited the changes on this file on the initial PR

plex auto lang - fix migration

---

ix-dev/stable/pihole/app.yaml
ix-dev/stable/pihole/migrations/migrate_from_kubernetes
ix-dev/stable/pihole/questions.yaml
ix-dev/stable/pihole/templates/docker-compose.yaml
ix-dev/stable/pihole/templates/library/base_v1_0_0/storage.py
ix-dev/stable/pihole/templates/library/base_v1_0_0/utils.py
ix-dev/stable/pihole/templates/test_values/basic-values.yaml
ix-dev/stable/pihole/templates/test_values/dhcp-values.yaml

Updates to sync with this:
https://github.com/truenas/charts/pull/2774

allow changing interface name

---

ix-dev/community/plex-auto-languages/app.yaml
ix-dev/community/plex-auto-languages/templates/docker-compose.yaml

plex-auto-languages: fix typo

---

.github/renovate-config.js
.github/scripts/renovate_bump.sh

https://github.com/truenas/apps_validation/pull/49

split enterprise in their own group and extend the params

---

.github/scripts/renovate_bump.sh

Was grepping the wrong string, resulting in multiple bumps on apps with multiple images

CI: grep the correct string

---

ix-dev/community/prowlarr/app.yaml
ix-dev/community/prowlarr/ix_values.yaml

prowlarr: fix name

---

ix-dev/community/rsyncd/app.yaml
ix-dev/community/rsyncd/questions.yaml
ix-dev/community/webdav/app.yaml
ix-dev/community/webdav/questions.yaml

Regression from https://github.com/truenas/apps/pull/294.
Those 2 apps use custom schema for storage (shares/modules)
FIxes https://github.com/truenas/charts/issues/2783

webdav/rsync: fix question regression

---

ix-dev/community/minecraft/app.yaml
ix-dev/community/minecraft/questions.yaml
ix-dev/community/unifi-protect-backup/app.yaml
ix-dev/community/unifi-protect-backup/questions.yaml

Did a regex search, does not seem to be any other similar issue

fix 2 naming issues

---

ix-dev/stable/pihole/app.yaml
ix-dev/stable/pihole/templates/docker-compose.yaml

Fixes https://github.com/truenas/apps/issues/329

pihole: fix perms

---

ix-dev/stable/storj/app.yaml
ix-dev/stable/storj/templates/library/base_v1_0_1/environment.py

Updates lib on storj. missed last small change

update storj lib

---

ix-dev/community/unifi-controller/app.yaml
ix-dev/community/unifi-controller/questions.yaml
ix-dev/community/unifi-controller/templates/docker-compose.yaml

unifi-controller: update wording on ports and add additional port

---

ix-dev/community/webdav/app.yaml
ix-dev/community/webdav/templates/webdav_macros/webdav_core.conf

Fixes https://github.com/truenas/apps/pull/146#issuecomment-2344171345

webdav: add missing slash on alias

---

.github/renovate-config.js

renovate: fix expression

---

ix-dev/community/sabnzbd/app.yaml
ix-dev/community/sabnzbd/questions.yaml

THis is to match https://github.com/truenas/charts/blob/master/community/sabnzbd/1.3.1/questions.yaml#L97C1-L98C1

sabnzbd: update default suggested web_port to 30055 to match original chart

---

ix-dev/stable/storj/app.yaml
ix-dev/stable/storj/templates/docker-compose.yaml

storj: fix storage var

---

ix-dev/community/gitea/app.yaml
ix-dev/community/gitea/templates/docker-compose.yaml

https://ixsystems.atlassian.net/browse/NAS-131029
https://github.com/go-gitea/gitea/blob/f05d9c98c4cb95e3a8a71bf3e2f8f4529e09f96f/docker/rootless/usr/local/bin/docker-setup.sh#L11

gitea: fix temp perms

---

ix-dev/community/minecraft/app.yaml
ix-dev/community/minecraft/questions.yaml
ix-dev/community/minecraft/templates/docker-compose.yaml
ix-dev/community/minecraft/templates/test_values/java11-j9-vanilla-values.yaml
ix-dev/community/minecraft/templates/test_values/java11-jdk-vanilla-values.yaml
ix-dev/community/minecraft/templates/test_values/java11-vanilla-values.yaml
ix-dev/community/minecraft/templates/test_values/java17-alpine-vanilla-values.yaml
ix-dev/community/minecraft/templates/test_values/java17-gce-vanilla-values.yaml
ix-dev/community/minecraft/templates/test_values/java17-j9-vanilla-values.yaml
ix-dev/community/minecraft/templates/test_values/java17-jdk-vanilla-values.yaml
ix-dev/community/minecraft/templates/test_values/java17-vanilla-values.yaml
ix-dev/community/minecraft/templates/test_values/java19-vanilla-values.yaml
ix-dev/community/minecraft/templates/test_values/java21-alpine-vanila-values.yaml
ix-dev/community/minecraft/templates/test_values/java21-graalvm-vanila-values.yaml
ix-dev/community/minecraft/templates/test_values/java21-vanila-values.yaml
ix-dev/community/minecraft/templates/test_values/java8-gce-vanilla-values.yaml
ix-dev/community/minecraft/templates/test_values/java8-j9-vanilla-values.yaml
ix-dev/community/minecraft/templates/test_values/java8-jdk-vanilla-values.yaml
ix-dev/community/minecraft/templates/test_values/java8-vanilla-values.yaml

Fixes https://github.com/truenas/charts/issues/2764

minecraft: allow additional ports

---

ix-dev/community/node-red/app.yaml
ix-dev/community/node-red/questions.yaml
ix-dev/community/node-red/templates/docker-compose.yaml
ix-dev/community/node-red/templates/test_values/node14-values.yaml

https://ixsystems.atlassian.net/browse/TNCHARTS-1192
Fixes https://github.com/truenas/charts/issues/2620

node-red: allow additional ports

---

.github/scripts/renovate_bump.sh

Fixes #408 
Depends on https://github.com/truenas/apps_validation/pull/50

renovate: fix app_version bump

---

ix-dev/stable/wg-easy/README.md
ix-dev/stable/wg-easy/app.yaml

Fixes https://github.com/truenas/charts/issues/2808

wg easy update repo

---

ix-dev/community/paperless-ngx/app.yaml

https://ixsystems.atlassian.net/browse/NAS-131209

fix screenshots

---

ix-dev/stable/home-assistant/app.yaml
ix-dev/stable/home-assistant/templates/docker-compose.yaml
ix-dev/stable/home-assistant/templates/test_values/basic-values.yaml

Closes https://github.com/truenas/charts/issues/2728

home-assistant: add more default files

---

ix-dev/community/frigate/app.yaml
ix-dev/community/frigate/questions.yaml

frigate: fix missing question

---

ix-dev/community/frigate/app.yaml
ix-dev/community/frigate/questions.yaml
ix-dev/community/frigate/templates/docker-compose.yaml
ix-dev/community/frigate/templates/test_values/basic-values.yaml

https://ixsystems.atlassian.net/browse/NAS-131252

frigate: fix dataset name and template

---

ix-dev/community/palworld/app.yaml
ix-dev/community/palworld/questions.yaml

See: https://github.com/truenas/charts/pull/2814

palworld: set default value

---

ix-dev/community/tdarr/app.yaml
ix-dev/community/tdarr/questions.yaml

tdarr: fix questions

---

ix-dev/community/tdarr/app.yaml
ix-dev/community/tdarr/templates/docker-compose.yaml

tdarr: fix typo

---

.github/renovate-config.js

fix renovate config

---

ix-dev/community/rust-desk/app.yaml
ix-dev/community/rust-desk/questions.yaml

rust-desk: fix condition on showif

---

ix-dev/stable/storj/app.yaml
ix-dev/stable/storj/templates/docker-compose.yaml
ix-dev/stable/storj/templates/macros/init.sh

storj: work around long waiting

---

ix-dev/community/bazarr/app.yaml
ix-dev/community/bazarr/questions.yaml

Fixes https://github.com/truenas/charts/issues/2840

bazarr: add timezone selection

---

ix-dev/community/invidious/app.yaml
ix-dev/community/invidious/ix_values.yaml
ix-dev/community/invidious/questions.yaml
ix-dev/community/invidious/templates/docker-compose.yaml
ix-dev/community/invidious/templates/test_values/basic-values.yaml

https://ixsystems.atlassian.net/browse/NAS-131441

invidious: add inv-sig-helper

---

ix-dev/community/vikunja/app.yaml
ix-dev/community/vikunja/migrations/migrate_from_kubernetes

vikunja: fix typo

---

ix-dev/community/sftpgo/app.yaml
ix-dev/community/sftpgo/templates/docker-compose.yaml
ix-dev/community/sftpgo/templates/test_values/plugins-values.yaml

sftpgo: fix checks

---

ix-dev/community/invidious/app.yaml
ix-dev/community/invidious/questions.yaml
ix-dev/community/invidious/templates/docker-compose.yaml

invidious: sig helper should be on the main container attached

---

ix-dev/community/zerotier/app.yaml
ix-dev/community/zerotier/migrations/migrate_from_kubernetes
ix-dev/community/zerotier/templates/docker-compose.yaml

Fixes #587 
Fixes #593
Storage section was added ~4month ago. Some installations might not have it
CI failure are expected

zerotier: handle older installations on migration

---

ix-dev/community/qbittorrent/app.yaml
ix-dev/community/qbittorrent/ix_values.yaml
ix-dev/community/qbittorrent/questions.yaml
ix-dev/community/qbittorrent/templates/docker-compose.yaml
ix-dev/community/qbittorrent/templates/test_values/basic-values.yaml

qbit: allow choosing v4 image

---

ix-dev/community/minecraft/app.yaml
ix-dev/community/minecraft/templates/docker-compose.yaml

fix use of join in minecraft server docker-compose.yaml

---

ix-dev/community/adguard-home/app.yaml
ix-dev/community/adguard-home/questions.yaml
ix-dev/community/adguard-home/templates/docker-compose.yaml

https://ixsystems.atlassian.net/browse/NAS-131638

adguard: allow switching to https probes

---

ix-dev/community/zerotier/app.yaml
ix-dev/community/zerotier/questions.yaml
ix-dev/community/zerotier/templates/docker-compose.yaml
ix-dev/community/zerotier/templates/test_values/basic-values.yaml
ix-dev/community/zerotier/templates/test_values/no-host-values.yaml

zerotier: add storage

---

ix-dev/community/nginx-proxy-manager/app.yaml
ix-dev/community/nginx-proxy-manager/questions.yaml
ix-dev/community/nginx-proxy-manager/templates/docker-compose.yaml
ix-dev/community/nginx-proxy-manager/templates/test_values/basic-values.yaml

nginx-proxy-manager: allow setting additional ports

---

ix-dev/community/jellyfin/app.yaml
ix-dev/community/jellyfin/migrations/migrate_from_kubernetes

https://ixsystems.atlassian.net/browse/NAS-132066

jellyfin: make TZ on migration optional

---

ix-dev/community/handbrake/app.yaml
ix-dev/community/handbrake/questions.yaml

handbrake: add gpu support

---

ix-dev/community/nginx-proxy-manager/app.yaml
ix-dev/community/nginx-proxy-manager/questions.yaml

Needed for migrations
https://ixsystems.atlassian.net/browse/NAS-132079

nginx-proxy-manager: allow user/group 0

---

ix-dev/stable/nextcloud/app.yaml
ix-dev/stable/nextcloud/templates/docker-compose.yaml

nextcloud: fix typo

---

.github/renovate-config.js

ci: fix regex for jenkins

---

ix-dev/community/jellyfin/app.yaml
ix-dev/community/jellyfin/questions.yaml
ix-dev/community/jellyfin/templates/docker-compose.yaml
ix-dev/community/jellyfin/templates/test_values/https-values.yaml

jellyfin: map https port

---

.github/renovate-config.js

renovate: linuxserver versioning

---

.github/renovate-config.js

plex: fix plex versioning

---

ix-dev/community/clamav/app.yaml
ix-dev/community/clamav/templates/docker-compose.yaml

clamav: fix missing additional storage

---

ix-dev/community/uptime-kuma/app.yaml
ix-dev/community/uptime-kuma/templates/docker-compose.yaml

uptime-kuma: Add NET_RAW

---

ix-dev/stable/plex/app.yaml
ix-dev/stable/plex/questions.yaml

- Plex questions support setting labels

plex: add labels

---

ix-dev/stable/emby/app.yaml
ix-dev/stable/emby/templates/docker-compose.yaml

emby: remove unneeded code

---

ix-dev/community/actual-budget/app.yaml
ix-dev/community/postgres/app.yaml
ix-dev/community/wordpress/app.yaml
ix-dev/community/wordpress/templates/docker-compose.yaml

Closes #911 
https://ixsystems.atlassian.net/browse/NAS-132477
https://ixsystems.atlassian.net/browse/NAS-132479

apps: update categories

---

ix-dev/community/gaseous-server/app.yaml
ix-dev/community/gaseous-server/questions.yaml

to use host-volumes with the database

Update description for Gaseous storage volumes to give a hint as to how

---

ix-dev/stable/emby/app.yaml
ix-dev/stable/emby/questions.yaml

matches the restriction we had in charts

emby: relax restriction

---

ix-dev/community/qbittorrent/app.yaml
ix-dev/community/qbittorrent/templates/docker-compose.yaml

qbit: fix https probe

---

ix-dev/stable/collabora/app.yaml
ix-dev/stable/collabora/questions.yaml

Closes https://github.com/truenas/charts/issues/2941

collabora: better error message

---

ix-dev/community/eclipse-mosquitto/app.yaml
ix-dev/community/eclipse-mosquitto/questions.yaml

mosquitto: fix key name

---

ix-dev/community/calibre/app.yaml
ix-dev/community/calibre/questions.yaml
ix-dev/community/calibre/templates/docker-compose.yaml

calibre: use unique default ports

---

ix-dev/enterprise/asigra-ds-system/app.yaml
ix-dev/enterprise/asigra-ds-system/ix_values.yaml

Asked via mail from asigra to use pg v16

asigra: update postgres image

---

ix-dev/community/scrutiny/app.yaml
ix-dev/community/scrutiny/templates/docker-compose.yaml

scrutiny: add caps

---

ix-dev/community/qbittorrent/app.yaml
ix-dev/community/qbittorrent/questions.yaml

qbit: allow changing downloads type

---

cspell.config.yaml
ix-dev/community/ollama/app.yaml
ix-dev/community/ollama/ix_values.yaml
ix-dev/community/ollama/questions.yaml
ix-dev/community/ollama/templates/docker-compose.yaml
ix-dev/community/ollama/templates/test_values/basic-values.yaml

ollama: allow to choose rocm image

---

ix-dev/stable/ix-app/app.yaml
ix-dev/stable/ix-app/questions.yaml

ix-app: fix show_if

---

ix-dev/stable/photoprism/app.yaml
ix-dev/stable/photoprism/questions.yaml
ix-dev/stable/photoprism/templates/docker-compose.yaml

photoprism: make url more clear that needs scheme

---

ix-dev/community/netbootxyz/app.yaml
ix-dev/community/netbootxyz/templates/docker-compose.yaml

Fixes https://github.com/truenas/charts/issues/2984

netboot: fix port protocol

---

ix-dev/community/adguard-home/app.yaml
ix-dev/community/adguard-home/questions.yaml
ix-dev/community/adguard-home/templates/docker-compose.yaml

adguard: allow overriding https probe port

---

ix-dev/community/clamav/app.yaml
ix-dev/community/clamav/ix_values.yaml
ix-dev/community/clamav/templates/docker-compose.yaml

https://ixsystems.atlassian.net/browse/NAS-133023

clamav: add warnings

---

.github/scripts/changed_apps.py
.github/workflows/app-test-suite.yaml

Demo that proves this work here
https://github.com/truenas/apps/pull/1205

ci: make ci work with larger matrixes

---

ix-dev/stable/emby/app.yaml
ix-dev/stable/emby/questions.yaml

Invalid filter has been specified in questions.yaml.
Fix the filters provided in emby's questions.

NAS-133277 / 25.04 / Fix emby questions

---

ix-dev/stable/wg-easy/app.yaml
ix-dev/stable/wg-easy/templates/docker-compose.yaml

wg-easy: fix empty value

---

ix-dev/stable/nextcloud/app.yaml
ix-dev/stable/nextcloud/questions.yaml

Closes https://github.com/truenas/apps/issues/931

nextcloud: add link for migration steps

---

ix-dev/community/distribution/app.yaml
ix-dev/community/distribution/questions.yaml

distribution: fix schema

---

.github/renovate-config.js
cspell.config.yaml
ix-dev/community/uptime-kuma/app.yaml
ix-dev/community/uptime-kuma/ix_values.yaml

uptime-kuma: update image

---

.github/renovate-config.js
ix-dev/community/tailscale/app.yaml
ix-dev/community/tailscale/ix_values.yaml

tailscale: update image

---

ix-dev/community/terraria/app.yaml
ix-dev/community/terraria/questions.yaml
ix-dev/community/terraria/templates/docker-compose.yaml
ix-dev/community/terraria/templates/test_values/basic-values.yaml
ix-dev/community/terraria/templates/test_values/password-values.yaml
ix-dev/community/terraria/templates/test_values/vanilla-values.yaml

terraria: expose tshock port

---

ix-dev/community/adguard-home/app.yaml
ix-dev/community/adguard-home/questions.yaml
ix-dev/community/adguard-home/templates/docker-compose.yaml
ix-dev/community/adguard-home/templates/test_values/basic-values.yaml
ix-dev/community/adguard-home/templates/test_values/dhcp-values.yaml

adguard-home: allow exposing other ports

---

ix-dev/community/immich/app.yaml
ix-dev/community/immich/ix_values.yaml

A new Immich Version was released, this change will update the app to the newest version.
Also changes to official Immich Github CR Images, I hope this is okay? I am new and not quite sure why the other version was used, I'm open to changing it back if it has advantages :)
Please go easy on me as this is my first PR. Thanks! 😄

chore(immich): update version, change to ghcr.io

---

ix-dev/community/lyrion-music-server/app.yaml
ix-dev/community/lyrion-music-server/questions.yaml

lms: fix condition

---

ix-dev/community/romm/app.yaml

Somehow version was not bumped on the last PR. bumping to release the fixes.
Fixes https://github.com/truenas/apps/issues/1405

romm: bump version

---

ix-dev/community/steam-headless/app.yaml
ix-dev/community/steam-headless/questions.yaml

steam-headless: fix variable name in questions.yaml

---

ix-dev/stable/home-assistant/app.yaml
ix-dev/stable/home-assistant/item.yaml

Following https://github.com/truenas/apps/blob/master/ix-dev/community/zigbee2mqtt/item.yaml#L2C3-L2C18

feat(home-assistant): Move home assistant to home-automation category

---

ix-dev/community/calibre-web/app.yaml
ix-dev/community/calibre-web/questions.yaml
ix-dev/community/lyrion-music-server/app.yaml
ix-dev/community/lyrion-music-server/questions.yaml
ix-dev/stable/emby/app.yaml
ix-dev/stable/emby/questions.yaml

Those ports should not be shown when host net is enabled.

apps: hide some port on host net

---

ix-dev/community/homarr/app.yaml
ix-dev/community/homarr/questions.yaml

homarr: validate the string

---

ix-dev/community/calibre-web/app.yaml
ix-dev/community/calibre-web/questions.yaml

calibre-web: fix condition

---

.github/renovate-config.js

renovate: fix syntax

---

ix-dev/community/penpot/app.yaml
ix-dev/community/penpot/templates/docker-compose.yaml

Add Penpot tagging for TrueNAS

---

ix-dev/community/iconik-storage-gateway/app.yaml
ix-dev/community/iconik-storage-gateway/questions.yaml

iconik: fix schema

---

ix-dev/community/dozzle/app.yaml
ix-dev/community/dozzle/templates/docker-compose.yaml

dozzle: fix healthcheck

---

ix-dev/community/distribution/app.yaml
ix-dev/community/distribution/templates/docker-compose.yaml

distribution: use docker's init when ssl is enabled

---

ix-dev/community/zerotier/app.yaml
ix-dev/community/zerotier/questions.yaml

zerotier: allow setting config to tmpfs

---

ix-dev/stable/ix-app/app.yaml
ix-dev/stable/ix-app/questions.yaml
ix-dev/stable/ix-app/templates/docker-compose.yaml
ix-dev/stable/ix-app/templates/test_values/basic-values.yaml

ix-app: allow setting devices

---

ix-dev/community/lyrion-music-server/app.yaml
ix-dev/community/lyrion-music-server/questions.yaml
ix-dev/community/lyrion-music-server/templates/docker-compose.yaml

lyrion-music-server: allow setting host-net

---

ix-dev/stable/plex/app.yaml
ix-dev/stable/plex/templates/docker-compose.yaml

Looks like plex needs more permissive rights.
https://github.com/truenas/apps/issues/1570#issuecomment-2652475829

plex: more permissive tmpfs

---

ix-dev/community/duplicati/app.yaml
ix-dev/community/duplicati/questions.yaml

Add part that is missing from schema

duplicati: fix schema

---

ix-dev/community/omada-controller/app.yaml
ix-dev/community/omada-controller/templates/docker-compose.yaml

omada-controller: use udp for discovery ports

---

ix-dev/community/wordpress/README.md
ix-dev/community/wordpress/app.yaml
ix-dev/community/wordpress/questions.yaml

wordpress: fix casing

---

ix-dev/community/minecraft-bedrock/app.yaml
ix-dev/community/minecraft-bedrock/item.yaml

minecraft-bedrock: fix item.yaml

---

ix-dev/community/terraria/app.yaml
ix-dev/community/terraria/templates/docker-compose.yaml

terraria: fix configpath

---

ix-dev/stable/nextcloud/app.yaml
ix-dev/stable/nextcloud/questions.yaml
ix-dev/stable/nextcloud/templates/test_values/basic-values.yaml

nextcloud: add libreoffice in the apt selection

---

ix-dev/community/tftpd-hpa/app.yaml
ix-dev/community/tftpd-hpa/templates/docker-compose.yaml

tftpd-hpa: bind port to udp instead of tcp

---

ix-dev/stable/nextcloud/app.yaml
ix-dev/stable/nextcloud/templates/macros/nc.jinja.conf

nextcloud: fix wellknown

---

ix-dev/community/calibre/app.yaml
ix-dev/community/calibre/templates/docker-compose.yaml

calibre: fix host-net

---

ix-dev/community/penpot/app.yaml
ix-dev/community/penpot/questions.yaml

penpot: add some defaults to make it easier to get started

---

ix-dev/community/jellyfin/app.yaml
ix-dev/community/jellyfin/questions.yaml
ix-dev/community/jellyfin/templates/docker-compose.yaml
ix-dev/community/jellyfin/templates/test_values/basic-values.yaml
ix-dev/community/jellyfin/templates/test_values/https-values.yaml

jellyfin: allow exposing discovery port

---

ix-dev/community/nginx-proxy-manager/app.yaml
ix-dev/community/nginx-proxy-manager/templates/docker-compose.yaml

nginx-proxy-manager: add dns for host-gateway

---

ix-dev/community/open-webui/app.yaml
ix-dev/community/open-webui/templates/docker-compose.yaml

open-webui: add host-gateway host

---

ix-dev/community/codegate/app.yaml
ix-dev/community/codegate/ix_values.yaml

codegate: remove config in wrong file

---

ix-dev/community/sftpgo/app.yaml
ix-dev/community/sftpgo/questions.yaml
ix-dev/community/sftpgo/templates/docker-compose.yaml
ix-dev/community/sftpgo/templates/test_values/basic-values.yaml
ix-dev/community/sftpgo/templates/test_values/https-values.yaml
ix-dev/community/sftpgo/templates/test_values/nosftp-values.yaml
ix-dev/community/sftpgo/templates/test_values/plugins-values.yaml

sftpgo: allow setting telemetry port

---

ix-dev/stable/pihole/app.yaml

pihole: update sources

---

ix-dev/stable/pihole/app.yaml
ix-dev/stable/pihole/questions.yaml
ix-dev/stable/pihole/templates/docker-compose.yaml
ix-dev/stable/pihole/templates/test_values/basic-values.yaml
ix-dev/stable/pihole/templates/test_values/dhcp-values.yaml

pihole: allow setting listenmode

---

ix-dev/community/minecraft-bedrock/app.yaml
ix-dev/community/minecraft/app.yaml

Those title for the app page are more explicit, adding the word server indicate that those apps are not the game itself. 
Clarity is improved despite beeing implied. 
Gramatically, there was too many capital letters, **this is purely cosmetic**.

Better name and description for minecraft

---

ix-dev/community/minecraft-bedrock/app.yaml
ix-dev/community/minecraft-bedrock/questions.yaml

this description would resolve issues by making people aware of the way the server is updated when game is updated.

add description for version

---

.github/scripts/ci.py

After this CI started failing. https://github.com/truenas/apps_validation/pull/67
This fixes permissions (kinda bluntly).
Tried directly running os.chmod, but the script itself didnt have the required permissions to do so.

fix rendered file perms for ci

---

.github/renovate-config.js

fix terraria versioning

---

ix-dev/community/minecraft-bedrock/app.yaml
ix-dev/community/minecraft-bedrock/templates/docker-compose.yaml

minecraft-bedrock: fix var

---

ix-dev/community/homepage/app.yaml
ix-dev/community/homepage/questions.yaml
ix-dev/community/homepage/templates/docker-compose.yaml
ix-dev/community/homepage/templates/test_values/basic-values.yaml

homepage: hosts

---

ix-dev/community/jdownloader2/app.yaml
ix-dev/community/jdownloader2/questions.yaml

fix(jdownloader2) Fix incorrect config storage label

---

ix-dev/community/fscrawler/app.yaml
ix-dev/community/fscrawler/templates/docker-compose.yaml

Use upstream provided entrypoint

fscrawler: fix entrypoint

---

ix-dev/community/jdownloader2/app.yaml
ix-dev/community/jdownloader2/ix_values.yaml
ix-dev/community/jdownloader2/templates/docker-compose.yaml

feat: add notes to jdownloader2

---

ix-dev/community/immich/app.yaml
ix-dev/community/immich/ix_values.yaml
ix-dev/community/immich/questions.yaml

immich: add rocm image for ML

---

ix-dev/enterprise/ix-remote-assist/app.yaml

https://ixsystems.atlassian.net/browse/NAS-134976

ix-remote-assist: update description

---

ix-dev/community/authentik/app.yaml
ix-dev/community/authentik/templates/docker-compose.yaml

authentik: explicitly listen to all interfaces

---

ix-dev/community/forgejo/app.yaml
ix-dev/community/forgejo/questions.yaml

forgejo: fix schema

---

ix-dev/stable/photoprism/app.yaml
ix-dev/stable/photoprism/questions.yaml

photoprism: allow RO for originals

---

ix-dev/stable/pihole/app.yaml
ix-dev/stable/pihole/templates/docker-compose.yaml

Closes https://github.com/truenas/apps/issues/1959

pihole: actually expose port

---

ix-dev/community/immich/app.yaml
ix-dev/community/immich/questions.yaml
ix-dev/community/immich/templates/docker-compose.yaml
ix-dev/community/immich/templates/test_values/basic-values.yaml

immich: allow setting mlcache storage

---

ix-dev/community/outline/app.yaml
ix-dev/community/outline/questions.yaml
ix-dev/community/outline/templates/test_values/basic-values.yaml
ix-dev/community/outline/templates/test_values/https-values.yaml

outline: fix schema

---

ix-dev/community/satisfactory-server/app.yaml
ix-dev/community/satisfactory-server/questions.yaml
ix-dev/community/satisfactory-server/templates/docker-compose.yaml
ix-dev/community/satisfactory-server/templates/test_values/basic-values.yaml

satisfactory: add messaging port

---

ix-dev/stable/pihole/app.yaml
ix-dev/stable/pihole/templates/docker-compose.yaml

pihole: fix cap and healthcheck

---

ix-dev/community/handbrake-web/app.yaml
ix-dev/community/handbrake-web/questions.yaml

handbrake-web: fix schema

---

ix-dev/community/eclipse-mosquitto/app.yaml
ix-dev/community/eclipse-mosquitto/ix_values.yaml
ix-dev/community/eclipse-mosquitto/templates/docker-compose.yaml

mqtt: add notes

---

ix-dev/community/calibre/app.yaml
ix-dev/community/calibre/ix_values.yaml
ix-dev/community/calibre/questions.yaml
ix-dev/community/calibre/templates/docker-compose.yaml

add warning for calibre

---

ix-dev/community/webdav/app.yaml
ix-dev/community/webdav/migrations/migrate_from_kubernetes

webdav: fix migration

---

ix-dev/community/warracker/app.yaml
ix-dev/community/warracker/questions.yaml

Warracker: Add uploads question to storage configuration

---

ix-dev/community/outline/app.yaml
ix-dev/community/outline/questions.yaml

outline: increase app private key length

---

ix-dev/community/electrs/app.yaml

Discovered this was missing on a test

Add some metadata to new electrs app

---

ix-dev/community/crafty-4/app.yaml
ix-dev/community/crafty-4/questions.yaml
ix-dev/community/crafty-4/templates/docker-compose.yaml
ix-dev/community/crafty-4/templates/test_values/basic-values.yaml

crafty-4: allow adding port ranges

---

ix-dev/stable/diskoverdata/app.yaml
ix-dev/stable/diskoverdata/templates/diskover_macros/fix-nginx.sh
ix-dev/stable/diskoverdata/templates/diskover_macros/setup-cron.sh
ix-dev/stable/diskoverdata/templates/docker-compose.yaml

Moves crontab setup into the custom-init, so it runs after built-in setup is completed.
Also added a check that file exists before trying to grep it, to reduce log-spam

diskoverdata: fix indexing additional storage

---

ix-dev/community/concourse/app.yaml
ix-dev/community/concourse/questions.yaml

fix concourse deployment issue caused by incorrect capitalization

---

ix-dev/community/newt/app.yaml
ix-dev/community/newt/questions.yaml

newt: fix schema

---

.github/renovate-config.js
ix-dev/community/kasm-workspaces/app.yaml
ix-dev/community/kasm-workspaces/ix_values.yaml

kasm: fix version

---

ix-dev/stable/netdata/app.yaml
ix-dev/stable/netdata/questions.yaml
ix-dev/stable/netdata/templates/docker-compose.yaml

netdata: fix template

---

ix-dev/community/komodo/app.yaml
ix-dev/community/komodo/questions.yaml

komodo: fix schema

---

ix-dev/community/gitea-act-runner/app.yaml
ix-dev/community/gitea-act-runner/questions.yaml
ix-dev/community/gitea-act-runner/templates/docker-compose.yaml
ix-dev/community/gitea-act-runner/templates/test_values/basic-values.yaml

gitea-act-runner: allow adding ports

---

ix-dev/community/dawarich/app.yaml

Added date was set to June 14 - corrected to May 14

Typo fix for Dawarich

---

ix-dev/community/n8n/app.yaml
ix-dev/community/n8n/templates/docker-compose.yaml

Closes https://github.com/truenas/apps/issues/2277

n8n: set npm cache dir to an existing volume

---

ix-dev/community/automatic-ripping-machine/app.yaml
ix-dev/community/automatic-ripping-machine/ix_values.yaml
ix-dev/community/automatic-ripping-machine/templates/docker-compose.yaml

arm: fix healthcheck

---

ix-dev/stable/ix-app/app.yaml
ix-dev/stable/ix-app/questions.yaml

We dont have to validate container port with this ref

custom-app: fix ports

---

ix-dev/stable/diskoverdata/app.yaml
ix-dev/stable/diskoverdata/templates/docker-compose.yaml

diskoverdata: fix elastic pass

---

ix-dev/community/mempool/app.yaml
ix-dev/community/mempool/templates/docker-compose.yaml

mempool: add portal

---

ix-dev/community/sftpgo/app.yaml
ix-dev/community/sftpgo/migrations/ip_port_migration

sftpgo: fix migration

---

ix-dev/community/uptime-kuma/app.yaml
ix-dev/community/uptime-kuma/templates/docker-compose.yaml

uptime-kuma: remove hardcoded host

---

ix-dev/community/ipfs/app.yaml
ix-dev/community/ipfs/templates/macros/init.sh.jinja

ipfs: fix listening on both v4 and v6 inside container

---

ix-dev/community/automatic-ripping-machine/app.yaml
ix-dev/community/automatic-ripping-machine/templates/docker-compose.yaml

arm: fix cd mount

---

ix-dev/community/cloudflared/app.yaml
ix-dev/community/cloudflared/ix_values.yaml
ix-dev/community/cloudflared/templates/docker-compose.yaml

cloudflared: fix args

---

ix-dev/community/dawarich/app.yaml
ix-dev/community/dawarich/app_migrations.yaml
ix-dev/community/dawarich/migrations/insert_redis_password_field_and_remove_db_data

dawarich: fix migration

---

ix-dev/community/traccar/app.yaml
ix-dev/community/traccar/questions.yaml

traccar: fix schema

---

ix-dev/community/frigate/app.yaml
ix-dev/community/frigate/templates/docker-compose.yaml

frigate: fix rendering when host net is enabled

---

.github/renovate-config.js
ix-dev/community/factorio/app.yaml
ix-dev/community/factorio/ix_values.yaml

Changed version in app and ix_values to stable-2.0.55 and added custom customVersioning to renovate-config.js as discussed [here](https://github.com/truenas/apps/pull/2644)

Factorio: Adjust version from latest to stable using custom Versioning

---

ix-dev/community/nginx-proxy-manager/app.yaml
ix-dev/community/nginx-proxy-manager/questions.yaml

npm: update description

---

ix-dev/community/eclipse-mosquitto/app.yaml
ix-dev/community/eclipse-mosquitto/questions.yaml
ix-dev/community/eclipse-mosquitto/templates/docker-compose.yaml
ix-dev/community/eclipse-mosquitto/templates/test_values/basic-values.yaml

mosquitto: allow configuring additional ports

---

ix-dev/community/outline/app.yaml
ix-dev/community/outline/questions.yaml

outline: only allow hex values

---

ix-dev/community/urbackup/app.yaml
ix-dev/community/urbackup/ix_values.yaml
ix-dev/community/urbackup/questions.yaml
ix-dev/community/urbackup/templates/docker-compose.yaml
ix-dev/community/urbackup/templates/test_values/basic-values.yaml
ix-dev/community/urbackup/templates/test_values/host-networking-true.yaml

urbackup: expose logs storage

---

ix-dev/stable/netdata/app.yaml
ix-dev/stable/netdata/templates/docker-compose.yaml

netdata: set hostname

---

ix-dev/stable/storj/app.yaml
ix-dev/stable/storj/templates/docker-compose.yaml

storj: fix template with hostnet enabled

---

ix-dev/community/immich/app.yaml
ix-dev/community/immich/templates/docker-compose.yaml

immich: remove variable

---

ix-dev/community/frigate/app.yaml
ix-dev/community/frigate/app_migrations.yaml
ix-dev/community/frigate/ix_values.yaml
ix-dev/community/frigate/migrations/hailo_image_migration
ix-dev/community/frigate/questions.yaml

See https://github.com/blakeblackshear/frigate/pull/16487

frigate: remove hailo image, its baked in main image now

---

ix-dev/community/transmission/app.yaml
ix-dev/community/transmission/app_migrations.yaml
ix-dev/community/transmission/migrations/incomplete_dir_migration
ix-dev/community/transmission/questions.yaml
ix-dev/community/transmission/templates/docker-compose.yaml
ix-dev/community/transmission/templates/test_values/basic-values.yaml

transmission: fix incomplete storage

---

ix-dev/community/bitcoind-knots/app.yaml
ix-dev/community/bitcoind-knots/questions.yaml
ix-dev/community/bitcoind-knots/templates/docker-compose.yaml

fix bitcoin knots defaults and datacarrier 

---

ix-dev/stable/storj/app.yaml
ix-dev/stable/storj/app_migrations.yaml
ix-dev/stable/storj/migrations/auth_token_rm_migration
ix-dev/stable/storj/questions.yaml
ix-dev/stable/storj/templates/docker-compose.yaml
ix-dev/stable/storj/templates/macros/init.sh
ix-dev/stable/storj/templates/test_values/basic-values.yaml

It's not required any more: https://forum.storj.io/t/identity-signing-identity-authorize-is-not-required-any-more/30581
See also: https://github.com/storj/docs/pull/586

storj: remove the requirement of the authorization step

---

ix-dev/community/paperless-ngx/app.yaml
ix-dev/community/paperless-ngx/templates/docker-compose.yaml

Solve unrelated issue found in #3051

paperless-ngx: fix tika healthcheck

---

ix-dev/test/nextcloud/app.yaml
ix-dev/test/nextcloud/templates/macros/nginx.conf

See https://github.com/nextcloud/docker/pull/2458

nextcloud/test: remove mime type

---

.github/ISSUE_TEMPLATE/app-request.yaml
.github/ISSUE_TEMPLATE/bug-report.yaml
.github/ISSUE_TEMPLATE/enhancement-request.yaml

Adds 2 issue templates. it will probably need to be adjusted a bit. But its a good starting point I think
Preview https://github.com/stavros-k/truenas-apps/issues

add issue templates

---

ix-dev/community/fileflows/app.yaml
ix-dev/community/fileflows/templates/docker-compose.yaml

fileflows: remove no-new-privileges sec opt

---

ix-dev/community/booklore/app.yaml
ix-dev/community/booklore/questions.yaml

booklore: expose db settings

---

ix-dev/community/unifi-controller/app.yaml
ix-dev/community/unifi-controller/questions.yaml
ix-dev/community/unifi-controller/templates/docker-compose.yaml
ix-dev/community/unifi-controller/templates/test_values/basic-values.yaml
ix-dev/community/unifi-controller/templates/test_values/https-values.yaml

unifi: expose stun port

---

ix-dev/community/speedtest-tracker/app.yaml
ix-dev/community/speedtest-tracker/questions.yaml

speedtest-tracker: add extra note

---

ix-dev/community/keycloak/app.yaml
ix-dev/community/keycloak/questions.yaml
ix-dev/community/keycloak/templates/docker-compose.yaml

keycloak: name hostname optional

---

ix-dev/stable/storj/app.yaml
ix-dev/stable/storj/templates/docker-compose.yaml
ix-dev/stable/storj/templates/macros/entrypoint.sh

storj: fix wallets

---

ix-dev/community/tiny-media-manager/app.yaml
ix-dev/community/tiny-media-manager/questions.yaml
ix-dev/community/tiny-media-manager/templates/docker-compose.yaml
ix-dev/community/tiny-media-manager/templates/test_values/basic-values.yaml

TinyMediaManager: allow adding extra ports

---

ix-dev/community/retrom/app.yaml
ix-dev/community/retrom/questions.yaml

retrom: fix schema
