truenas/apps

.github/workflows/update_catalog.yaml
This PR makes sure we don't trigger update catalog action for commits which were created by the gh action itself.
=> NAS-129730 / 24.10 / Do not trigger update catalog action for commits created by action

.github/workflows/update_catalog.yaml
When there are no published apps, update catalog action would error out because it still tries to commit (part of it still commits where only date hashes are changed and published)
Skip the commit generation if nothing has changed in the repository.
=> NAS-129729 / 24.10 / Properly mark github action as success if nothing has been published

.github/workflows/update_catalog.yaml
Properly expand `pwd` when tracking changed apps in gh action.
=> NAS-129945 / 24.10 / Fix GH action for updating catalog

features_capability.json
Document `node_bind_ip` ref in feature capability matrix.
=> NAS-130170 / 24.10 / Add node bind ip ref to feature capability matrix

.github/workflows/update_catalog.yaml, ix-dev/community/node-red/app.yaml, ix-dev/community/node-red/item.yaml
Currently when 2 PRs are merged at the same time, update catalog will most likely fail.
Catalog update performs 2 commits, which between them the second catalog update can attempt to commit.
Solution:
Lock the catalog update concurrency to a single run at a time.
So newer catalog update workflows will be queued.
---
Also fixes a typo that leads to a CI failure here
https://github.com/truenas/apps/actions/runs/10248348970/job/28349443068
=> lock concurrency on catalog update

ix-dev/community/zerotier/app.yaml, ix-dev/community/zerotier/templates/docker-compose.yaml, ix-dev/community/zerotier/templates/test_values/basic-values.yaml
Docker expects string in the command array, We should make sure its always a string
Also fixes https://github.com/truenas/charts/issues/2708#issuecomment-2284754762
=> zerotier: make sure netid is quoted

ix-dev/stable/nextcloud/app.yaml, ix-dev/stable/nextcloud/templates/docker-compose.yaml
During migration the host is different than what it was in k8s.
This updates hosts in the config file, because nextcloud does not use the envvars to update those fields after initial installation.
=> nextcloud: add hook script to update db/redis host

.github/scripts/ci.py, ix-dev/community/bazarr/app.yaml, ix-dev/community/bazarr/ix_values.yaml
Docker daemon will exit with a non-zero code if a container exits with `0`.
Such case is init containers.
So we inspect containers to identify if it was actually a failure or not.
But if daemon failed to start all containers, the "failed" containers will always be 0, so we marked it as "success".
Such case is if the image is wrongly typed. (See app in this PR which had this issue and the commits before and after the change)
This PR checks that at least 1 container exists before starting checking for failed containers.
if there is none, it will fail the ci run.
Did a test run across all apps here to see if there was any other issues https://github.com/truenas/apps/pull/124
All seems to be good!
=> App ci tester wouldnt fail if it failed to start any containers at all

ix-dev/community/chia/app.yaml, ix-dev/community/chia/questions.yaml
@Qubad786 
Can we add validation that the `default` value is one of the `enum` that is defined?
=> fix chia's default enum value

ix-dev/community/adguard-home/app.yaml, ix-dev/community/adguard-home/ix_values.yaml, ix-dev/community/adguard-home/templates/docker-compose.yaml
Fixes #283 
Surprisingly, docker will not do anything on unhealthy containers.
Will just provide info about that.
On initial setup, adguard allows users to setup the web port which defaults to `80`.
Even if we use the `--port` flag. 
While the `--port` flag has priority, the wizard will temporary set the port to 80. Which is why the restart is required, so the flag will take effect.
Previously we relied on k8s to restart the container once the probe started failing (due to the changed port).
But docker does not do that. It will only restart a container that is `exited`
=> add note for initial setup

ix-dev/community/qbittorrent/app.yaml, ix-dev/community/qbittorrent/templates/docker-compose.yaml
This fixes a typo in the qBittorrent docker compose file, where the qBittorrent config volume configuration is used for the downloads volume.
=> qBittorrent: Use correct downloads volume configurations

ix-dev/community/freshrss/app.yaml, ix-dev/community/freshrss/templates/docker-compose.yaml
Similar to #334, this fixes the reuse of a volume path variable.
After #334, I quickly looked for similar problems and found this one. Please note, I did not test this fix, but from looking at the template, I believe `values.storage.extensions` is correct (as it is not used anywhere else).
=> FreshRSS: Use correct extensions volume config

.github/renovate-config.js
Lets bump `patch` version on apps when a container updates.
---
If we keep the bump type to whatever the container update type is, all Date Versioned containers will be at minimum a `minor` bump.
=> do a patch bump on container updates

ix-dev/stable/ix-app/app.yaml, ix-dev/stable/ix-app/migrations/migrate_from_kubernetes, ix-dev/stable/ix-app/migrations/migration_helpers/cpu.py, ix-dev/stable/ix-app/migrations/migration_helpers/memory.py, ix-dev/stable/ix-app/migrations/migration_helpers/resources.py, migration_helpers/cpu.py, migration_helpers/memory.py, migration_helpers/resources.py
Fixes issue spotted in https://github.com/truenas/middleware/pull/14486 (2 typos in the migration script)
Also noticed that cpu/memory might result in float or 0.
Changes applied to handle that case as well.
=> ix-app: fix migration

.github/renovate-config.js
Fixes #390 
Renovate does not support negative lookahead.
=> remove negative lookahead regex

ix-dev/stable/nextcloud/app.yaml, ix-dev/stable/nextcloud/questions.yaml
Fixes https://github.com/truenas/charts/issues/2078
I couldn't find any additional dependencies needed gpu is used.
We can come back to this if we see any issues when consuming one.
(Library should pick up the gpu's from questions and map them automatically)
=> nextcloud: add gpu questions

ix-dev/community/paperless-ngx/app.yaml, ix-dev/community/paperless-ngx/templates/docker-compose.yaml
Basic paperless-ngx setup leaves env variable PAPERLES_CONSUMPTION_PATH empty. Suspect that it's just a typo here.
=> Fix paperless-ngx wrong consumption dir env variable

.github/scripts/ci.py, ix-dev/community/navidrome/app.yaml, ix-dev/community/navidrome/templates/docker-compose.yaml, ix-dev/community/navidrome/templates/test_values/basic-values.yaml
Adds another sanity check on ci.py to catch cases where some containers do not start at all, for various reasons.
(eg a host device is not available, or an image cannot be resolved)
This is usually marked as "daemon error"
Fixes navidrome as well
=> navidrome: fix healthcheck

ix-dev/community/frigate/app.yaml, ix-dev/community/frigate/questions.yaml
I'm not sure if this is the correct way to do this, but there seems to be a weird issue where subquestions are only shown when host network check is selected on frigate setup. And due to it binding to host network, these port setting are not respected  e.g. my frigate app is currently available on port 8971 which is frigate default and not 30058 which is what is set in the config. I strongly suspect this is due to the erroneous true set for subquestions. If this is not the right way to do this, please do the needful so frigate could be configured properly.
=> set erroneous true to false

ix-dev/stable/plex/app.yaml, ix-dev/stable/plex/migrations/migrate_from_kubernetes, ix-dev/stable/plex/questions.yaml, ix-dev/stable/plex/templates/docker-compose.yaml, ix-dev/stable/plex/templates/test_values/basic-values.yaml, ix-dev/stable/plex/templates/test_values/hostnet-values.yaml
Fixes https://ixsystems.atlassian.net/browse/NAS-131408
Fixes https://github.com/truenas/charts/issues/2741
FIxes https://github.com/truenas/charts/issues/2564
---
Allowed networks are also used by plex to show (or not) the initial setup page.
When plex runs in non-hostnetwork-ed container, it won't show the setup page, as it ONLY considers "local" the docker network. Which the user browser is most definitely not.
I've set as defaults all the private ranges.
On users migrating from DF, it will either keep the existing (no networks defined) or migrate if they have manually set the ALLOWED_NETWORKS variable.
=> plex: add allowed networks

.github/scripts/renovate_bump.sh
it was never setting the `update_type` to `""` due to bad syntax.
This resulted in bumping the same app multiple times if more than 1 images were updated
=> ci: fix typo

ix-dev/community/lidarr/app.yaml, ix-dev/community/lidarr/ix_values.yaml, ix-dev/community/lidarr/templates/docker-compose.yaml
Old image source deprecated the lidarr image.
Switching to a drop-in replacement that is currently maintained
=> lidarr: switch upstream image source

ix-dev/community/freshrss/app.yaml, ix-dev/community/freshrss/ix_values.yaml, ix-dev/community/freshrss/migrations/migrate_from_kubernetes, ix-dev/community/freshrss/questions.yaml, ix-dev/community/freshrss/templates/docker-compose.yaml, ix-dev/community/freshrss/templates/test_values/basic-values.yaml
Fixes #607 
Moves the 2 keys to questions as hidden 
and default to what we had on ix_values (this should keep existing users that installed fresh on EE to continue work without issues.
For users migrating from DF, we will pull those from helm secrets, and update the hidden fields in questions
=> freshrss: fix migration

ix-dev/community/tailscale/app.yaml, ix-dev/community/tailscale/templates/docker-compose.yaml, ix-dev/community/tailscale/templates/library/community/tailscale/v1_1_12/util.py
Fixes #616 
- Removes the validation for auth key format, as third party servers might user different format
- Makes sure that `--authkey` can't be passed via extra params, as users should use the dedicated fields.
=> tailscale: dont restrict auth key format

ix-dev/stable/photoprism/app.yaml, ix-dev/stable/photoprism/migrations/migrate_from_kubernetes
Fixes #623 
Given that only 2 fields were added on the latest photoprism questions compared to the user's version. We can handle that migration gracefully.
=> photoprism: handle gracefully some fields

ix-dev/stable/syncthing/app.yaml, ix-dev/stable/syncthing/questions.yaml
We didn't had such restriction on k8s, so it was breaking some migrations.
=> syncthing/stable: remove restriction on user/group ids

ix-dev/community/rsyncd/app.yaml, ix-dev/community/rsyncd/templates/rsync_macros/rsyncd.conf
- We were validating the top level aux params but not per module
- bool values have to be `true` and not `True`
=> rsyncd: fix conf bool values and validate module's aux params

.github/workflows/renovate.yaml
Sets renovate log level to debug.
I'm trying to debug why it won't open a PR for some apps.
=> set renovate logs to debug

.github/renovate-config.js, ix-dev/stable/plex/app.yaml, ix-dev/stable/plex/migrations/migrate_from_kubernetes
We validate that user's wont try to override variables that we automatically set.
In this case a user had this variable set when migrating from kubernetes and the template generation was failing after the migration.
We did have some validation in k8s for this as well, but there was a small escape hatch apparently.
We might see this issue in other apps that can potentially utilize nvidia gpu's, even if we didnt expose the setting.
=> plex: handle some very niche case for migration

ix-dev/community/rsyncd/app.yaml, ix-dev/community/rsyncd/templates/docker-compose.yaml
See a description in Issue #705.
I'm not entirely sure how to switch to another repo to get apps from yet, but I did try making the same change locally in `/mnt/.ix-apps/app_configs/rsyncd/versions/1.0.14/templates/docker-compose.yaml` then made a config change to the app so it redeployed and it appears to have the correct capabilities now and I can use the rsync daemon on the version of Electric Eel mentioned in the issue.
I did see that the repo says no PRs right now, but figured this should be pretty straightfoward and I may as well submit a single line change.
=> rsyncd: fix to add capabilities in compose template

ix-dev/community/ddns-updater/app.yaml, ix-dev/community/ddns-updater/templates/library/community/ddns-updater/v1_0_27/config.py, ix-dev/community/ddns-updater/templates/test_values/noip-values.yaml
Makes sure that even if numbers are passed in a string field, they remain a string.
https://ixsystems.atlassian.net/browse/TNCHARTS-1484
Fixes https://github.com/truenas/charts/issues/2913
=> ddns-updater: handle field types

ix-dev/stable/nextcloud/app.yaml, ix-dev/stable/nextcloud/templates/docker-compose.yaml
Fixes https://github.com/truenas/charts/issues/2908
Nextcloud does not resolve hosts in trusted proxies.
Considering this is an **install only** env-variable, I'll set the trusted proxies to all private network ranges.
From there users can adapt to their preferred values,
=> nextcloud: fix trusted-proxies warning

.github/renovate-config.js
- Removes the group, so each enterprise app will be in a separate PR.
- The PR will include the latest release that is at least 21days out there.
=> renovate: enterprise versioning

ix-dev/stable/storj/app.yaml, ix-dev/stable/storj/templates/macros/init.sh
Closes #788 
Checks if the directory is writable early, before the whole identity generation process happens.
=> storj: check early if configdir is writable

ix-dev/community/rsyncd/app.yaml, ix-dev/community/rsyncd/questions.yaml
UID/GID can be > 65535, for example in some AD domain situations. This PR allows UID/GID to be up to max int32 (4294967295) in rsyncd module UI
=> rsyncd : allow uid/gid > 65535

ix-dev/community/plex-auto-languages/app.yaml, ix-dev/community/plex-auto-languages/ix_values.yaml
Fixes #1113
New upstream does not have currently versioned tag, so switching to `latest` for now
=> pal: change upstream

ix-dev/community/briefkasten/app.yaml, ix-dev/community/briefkasten/item.yaml, trains/community/briefkasten/item.yaml
Hi, I'm one of the Homarr developers 👋
The screenshot for "Briefkasten" seem to accidentally use the incorrect screenshots from our app and not Briefkasten.
This commit copies the links from https://github.com/truenas/charts/blob/master/community/briefkasten/item.yaml  and removes the incorrect Homarr links.
=> config: update incorrect screenshots of briefkasten

ix-dev/stable/nextcloud/app.yaml, ix-dev/stable/nextcloud/templates/docker-compose.yaml, ix-dev/stable/nextcloud/templates/macros/nc.jinja.conf, ix-dev/stable/nextcloud/templates/test_values/basic-values.yaml, ix-dev/stable/nextcloud/templates/test_values/https-values.yaml, ix-dev/stable/nextcloud/templates/test_values/no-cron-values.yaml, ix-dev/stable/nextcloud/templates/test_values/same-vol-values.yaml
This PR renames `network.nginx.use_different_access_port` to `network.nginx.use_different_port` to fix the use of the different port as it is not picked up at the moment.
It also adds the domain with the different port to `NEXTCLOUD_TRUSTED_DOMAINS`.
=> fix(nextcloud): Rename network.nginx.use_different_access_port to network.nginx.use_different_port

ix-dev/community/gaseous-server/app.yaml, ix-dev/community/gaseous-server/ix_values.yaml, ix-dev/community/gaseous-server/templates/docker-compose.yaml
@stavros-k can you confirm I did this right? Not sure how to preview this locally. If I can use markdown in the YAML, that would be awesome as well. I'll update if so.
=> Add correct link to documentation for Gaseous in Notes

ix-dev/stable/nextcloud/app.yaml, ix-dev/stable/nextcloud/templates/macros/nc.jinja.sh
When nextcloud fails to fully complete an upgrade, some occ commands are not available.
Lets not exit and let container start so use can manually complete the upgrade.
Closes https://github.com/truenas/apps/issues/1156
=> nextcloud: don't make container restart if occ is not available

ix-dev/stable/nextcloud/app.yaml, ix-dev/stable/nextcloud/questions.yaml, ix-dev/stable/nextcloud/templates/docker-compose.yaml, ix-dev/stable/nextcloud/templates/macros/nc.jinja.sh
Nextcloud ignores NEXTCLOUD_TRUSTED_DOMAINS after initial install.
This PR makes changes to update the trusted_domains key in the config.php file.
In order to not break custom domains added from user, we fetch existing domains, append the domains we set in the NEXTCLOUD_TRUSTED_DOMAINS, deduplicate and set the list of domains again.
While it will help a bit, it still might require manual changes on the config file if user wants to _remove_ a previous trusted domain that was added via the Host field from UI.
=> nextcloud: update trusted domains on start

ix-dev/community/tailscale/app.yaml, ix-dev/community/tailscale/templates/docker-compose.yaml
as https://tailscale.com/kb/1282/docker#ts_tailscaled_extra_args say, we should pass tailscaled_args as env `TS_TAILSCALED_EXTRA_ARGS` instead of `TS_EXTRA_ARGS`
=> tailscale: correct tailscaled args env name

ix-dev/community/jelu/app.yaml, ix-dev/community/jelu/questions.yaml, ix-dev/community/jelu/templates/test_values/basic-values.yaml
Jelu runs as root, so those are not used
=> jelu: remove unused code

ix-dev/community/paperless-ngx/app.yaml, ix-dev/community/paperless-ngx/questions.yaml, ix-dev/community/paperless-ngx/templates/docker-compose.yaml, ix-dev/community/paperless-ngx/templates/test_values/tika-gotenberg-values.yaml
=> paperless: allow enabling js for gotenberg

.github/renovate-config.js, ix-dev/community/calibre-web/app.yaml, ix-dev/community/calibre-web/ix_values.yaml, ix-dev/community/calibre-web/questions.yaml, ix-dev/community/calibre-web/templates/docker-compose.yaml, ix-dev/community/calibre-web/templates/test_values/basic-values.yaml
Fixes https://github.com/truenas/apps/issues/1133
Previous upstream removed support for calibre-web, so bug wont be fixed nor updates would flow through.
This is a breaking change, hence the major version bump.
=> calibre-web: switch upstreams

.github/workflows/dev_apps_validate.yml
This workflow wasn't running for outside contributors. As the push event was happening on their fork.
=> ci: run dev app validation on contributors as well

ix-dev/community/paperless-ngx/app.yaml, ix-dev/community/paperless-ngx/questions.yaml, ix-dev/community/paperless-ngx/templates/docker-compose.yaml, ix-dev/community/paperless-ngx/templates/test_values/tika-gotenberg-values.yaml
=> paperless-ngx: use encoded url and allow changing the allow-list for chromium/gotenberg

ix-dev/community/esphome/app.yaml, ix-dev/community/esphome/ix_values.yaml, ix-dev/community/esphome/templates/docker-compose.yaml, ix-dev/community/esphome/templates/test_values/basic-values.yaml, ix-dev/community/esphome/templates/test_values/root-user.yaml
ive tested compiling several device types with these settings. It would be a bit more clean if we could override permissions on /piolibs in the container. The platformio builds fail because they cant read that folder. When i set the env var PLATFORMIO_GLOBALLIB_DIR to any other dir, builds work. I assume it doesnt find that local cache in the container and downloads a new copy.
This is working though. I added a new test case for running as root (which also worked). If there is a way to force uid 568 on /piolibs im happy to update the PR.
=> esphome: set two platformio env vars to allow esphome to run as non-root

ix-dev/community/sftpgo/app.yaml, ix-dev/community/sftpgo/templates/docker-compose.yaml, ix-dev/community/sftpgo/templates/test_values/nosftp-values.yaml
Disables the default sftp configuration as there is already a list to define additional sftp configurations in the UI form
=> sftpgo: disable sftp if non are defined

ix-dev/community/frigate/app.yaml, ix-dev/community/frigate/ix_values.yaml, ix-dev/community/frigate/questions.yaml, ix-dev/community/frigate/templates/docker-compose.yaml, ix-dev/community/frigate/templates/test_values/https-values.yaml
Location for certificates is taken from [Frigate documentation](https://docs.frigate.video/configuration/tls/)
=> feat(app) frigate: add SSL certificate configuration options and update templates

ix-dev/community/palworld/app.yaml, ix-dev/community/palworld/templates/docker-compose.yaml
The config storage wasn't shared with the init container, which resulted that init container was only modifying a throw-away file.
Fixes #1527
=> palworld: fix config initialization

ix-dev/community/steam-headless/app.yaml, ix-dev/community/steam-headless/templates/docker-compose.yaml
=> steam-headless: add mknod cap

ix-dev/community/zigbee2mqtt/app.yaml, ix-dev/community/zigbee2mqtt/questions.yaml
Looks like URI does not accept mqtt as scheme.
=> zigbee: revert schema type

ix-dev/stable/plex/app.yaml, ix-dev/stable/plex/templates/docker-compose.yaml
Closes #1570
Closes #1579
---
Plex starts sub-processes as different uid, so that uid cant write to tmpfs as docker creates it as root.
Set mode to allow "others" to rw.
=> plex: set mode for tmpfs

ix-dev/community/minecraft-bedrock/app.yaml, ix-dev/community/minecraft-bedrock/questions.yaml
In this [TrueNas forum](https://forums.truenas.com/t/minecraft-bedrock-app-not-recognizing-me-as-an-operator-in-game/35282?u=remdg) we can see that the set privilege field confuses people. 
This pull request add a description indicating how field have to be used, including the need to fill a player field with XUID. (People might have tried with gamertag, IP address or something else)
I also added the [URL ](https://www.cxkes.me/xbox/xuid) of a website that is able to extract the Xbox User ID from a gamertag and some links to the docker image documentation about permissions.
=> add description for game privileges fields

ix-dev/stable/nextcloud/app.yaml, ix-dev/stable/nextcloud/questions.yaml
In order to be able to migrate a deprecated configuration when using ix-volumes, changing storage type is allowed now.
Closes https://github.com/truenas/apps/issues/1382
=> nextcloud: allow changing storage type

.github/workflows/renovate.yaml
With the newer dockerhub rate-limits, renovate is hitting them more frequently, causing the whole run to fail.
This adds caching to prevent hitting the limits.
=> add renovate caching

ix-dev/community/scrutiny/app.yaml, ix-dev/community/scrutiny/questions.yaml, ix-dev/community/scrutiny/templates/docker-compose.yaml
It was requested to let scrutiny auto detect disks, instead of passing them one-by-one by hand
=> scrutiny: run privileged for automatic disk detection

ix-dev/community/authentik/app.yaml, ix-dev/community/authentik/questions.yaml
=> fix(Authentik): require redis password and fix label typo

ix-dev/community/monero-lws/app.yaml, ix-dev/community/monero-lws/templates/docker-compose.yaml, ix-dev/community/monero-lws/templates/macros/entrypoint.sh, ix-dev/community/monero-lws/templates/test_values/basic-values.yaml
We're disabling healthchecks since there isn't a good endpoint for that, all of them require auth, by mistake I thought `/` would work.
=> Monero LWS: fixes

ix-dev/community/bitcoind/app.yaml, ix-dev/community/bitcoind/questions.yaml, ix-dev/community/bitcoind/templates/docker-compose.yaml, ix-dev/community/bitcoind/templates/test_values/basic-values.yaml
@Keeqler While I found the correct syntax, UI currently does not take `OR` into account.
Removed the show_if completely, and shifted the validation to jinja.
For future ref, this is the correct format
```yaml
show_if:
- - OR
- - ["tor_outgoing_enabled", "=", true]
- ["clearnet_outgoing_via_tor_enabled", "=", true]
- ["tor_incoming_enabled", "=", true]
```
=> bitcoind: fix show_if filters

ix-dev/community/playwright/app.yaml, ix-dev/community/playwright/questions.yaml
Fix for playwright questions missing customer user entry.  I had removed it due to requiring npm cache to be overridden in order to use a user_id other than pwuser (1001).  That configuration was included in the final app design but missed adding back custom user entry.
=> Add back custom user for playwright

ix-dev/stable/pihole/app.yaml, ix-dev/stable/pihole/questions.yaml
Bind mode was missing.
There is some kind of conflict now that there is some dnsmasq using port 53 on libvirt bridges. I guess that's related to incus integration.
Bind mode allows pi-hole to start its dnsmas on a specific interface. pi-hole container can now work on 25.04.
=> Allow bind mode for DNS listening

ix-dev/community/pterodactyl-panel/app.yaml, ix-dev/community/pterodactyl-panel/templates/docker-compose.yaml
Pterodactyl panel has notes set in ix-values but doesn't show in the UI
=> Set notes in pterodactyl-panel

ix-dev/community/gramps-web/app.yaml, ix-dev/community/gramps-web/questions.yaml, ix-dev/community/gramps-web/templates/docker-compose.yaml, ix-dev/community/gramps-web/templates/test_values/basic-values.yaml
Gramps web allows running Machine Learning models within the container. It stores the models in a ./cache folder, which is not accessible when not run as a root. This PR mounts the ./cache folder as a temp volume and lets our permissions container take care of fixing the permissions of the directory.
Things to consider:
What is the lifetime of the temporary volume? Is it cleared on every reboot or duing container updates? If it gets cleared on every container reboot, we might want a different approach for this solution as models can be sometimes quire large. Clearing it on container updates seems right to me as a new update might include updated models and might not dispose of the old ones properly resulting in larger space being used.
closes: #2433
=> Gramps: Mount /.cache as a temp volume to allow usage of ML

cspell.config.yaml, ix-dev/community/gramps-web/app.yaml, ix-dev/community/gramps-web/ix_values.yaml, ix-dev/community/gramps-web/questions.yaml, ix-dev/community/gramps-web/templates/docker-compose.yaml, ix-dev/community/gramps-web/templates/test_values/basic-values.yaml
Running non-root causes lots of issues, that there is no known way to fix/workaround without modifying upstream code.
This PR changes to using root user for this app and also keeps the directory structure as is from upstream.
This means that users have to re-install and configure the storage from scratch.
If their current app works or at least partly works, they can probably export data from within the app UI and re-import on new install
Fixes #2514
=> gramps: fix relation tree

ix-dev/community/immich/app.yaml, ix-dev/community/immich/ix_values.yaml
After following the storage migration from 1.9.0, the server did not start up at first. I saw the following error printed:
```
[Nest] 7  - 06/14/2025, 3:14:40 PM   ERROR [Microservices:StorageService] Failed to read upload/upload/.immich: Error: ENOENT: no such file or directory, open 'upload/upload/.immich'
```
I had made a subdirectory called `uploads` on my new unified dataset, but it seems like it was supposed to be named `upload` instead. Renaming it to `upload` fixed the problem so I think the example command here should be updated.
I haven't contributed here before so please let me know if something's wrong or I need to do anything else to enable this change.
edit: I just noticed there are two other comments in the issue confirming this is necessary:
- …
=> immich: change "uploads" to "upload" in storage migration guide

ix-dev/community/kasm-workspaces/app.yaml, ix-dev/community/kasm-workspaces/ix_values.yaml
Kasm doesn't update automatically and the update has to be manually installed via the setup page after successful container update.
=> feat(kasm): add update instructions to notes
